backend: Clipboard

# verhindert viele Probleme mit Browsern, Electron Apps und Terminal
paste_shortcut: CTRL+V

# Expansion nur wenn ein Wort beendet ist
word_separators:
  - " "
  - "."
  - ","
  - "!"
  - "?"
  - "\n"

# erlaubt :trigger Format
search_shortcut: ALT+SPACE

# Log-Level (für Debugging)
log_level: warn
