name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest

    steps:
      # ----------------------------------------
      # CHECKOUT
      # ----------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ----------------------------------------
      # NODE SETUP
      # ----------------------------------------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ----------------------------------------
      # INSTALL DEPENDENCIES
      # ----------------------------------------
      - name: Install dependencies
        run: npm install

      # ----------------------------------------
      # SEMANTIC RELEASE
      # ----------------------------------------
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: semantic-release:*
        run: npx semantic-release
